<?php
/**
* * Implementation of hook_form_alter()
* */
function asc_people_filter_form_alter(&$form, $form_state, $form_id) {
    
    if ($form['#id'] == 'views-exposed-form-People-page-1') {
      $form['appt']['#options']['All'] = t('All');
    }

    if ($form['#id'] == 'views-exposed-form-People-page-2') {
      $form['area']['#options']['All'] = t('All');
    }

}

function asc_people_filter_block($op = 'list, $delta = 0, $edit = array()') {
  switch ($op) {
    case 'list':
      blocks[0]['info'] = t('Active Filters');
      blocks[0]['cache'] = BLOCK_NO_CACHE;
      return $blocks;

    case 'view':
      $terms = array();

      if (isset($_GET['area'])) {
        $terms[] = $_GET['area'];
      }

      if (isset($_GET['appt'])) {
        $terms[] = $_GET['appt'];
      }

      block['subject'] = t('Active Filters');
      block['content'] = theme('item_list',$terms);
  }

  
}

?>
