<?php
/**
* * Implementation of hook_form_alter()
* */
function asc_people_filter_form_alter(&$form, $form_state, $form_id) {
    
    if ($form['#id'] == 'views-exposed-form-People-page-1') {
      $form['appt']['#options']['All'] = t('All');
      $form['area']['#options']['All'] = t('All');
      dsm($form);
    }

}

function _people_get_exposed_filter_form(){
  $view = views_get_view('People');
  $view->set_display('page');
  $view->init_handlers();
  $exposed_form = $view->display_handler->get_plugin('exposed_form');
  dsm($exposed_form);
  return $exposed_form->render_exposed_form();
}

function asc_people_filter_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {
    case 'list':
      $blocks[0]['info'] = t('Active Filters');
      $blocks[0]['cache'] = BLOCK_NO_CACHE;
      $blocks[1]['info'] = t('Appointments');
      $blocks[2]['info'] = t('Research Interests');
      return $blocks;

    case 'view':
      if ($delta == 0) {
        $terms = array();

        if (isset($_GET['area']) && $_GET['area'] != "All") {
          $term = taxonomy_get_term($_GET['area']);
          $terms[] = $term->name;
        }

        if (isset($_GET['appt']) && $_GET['appt'] != "All") {
          $term = taxonomy_get_term($_GET['appt']);
          $terms[] = $term->name;
        }

        $block['subject'] = t('Active Filters');
        $block['content'] = theme('item_list',$terms);
      }      
      elseif ($delta == 1) {
        $block['content'] = drupal_get_form('views-exposed-form-People-page-1');
        dsm($block['content']);
        $block['subject'] = "";
      }
      elseif ($delta == 2) {
        $block['content'] = drupal_get_form('views-exposed-form-People-page-1');
        $block['subject'] = "";
      }
      return $block;
  }  
}

?>
