<?php
/**
* * Implementation of hook_form_alter()
* */
function asc_people_filter_form_alter(&$form, $form_state, $form_id) {
    
    if ($form['#id'] == 'views-exposed-form-People-page-1') {
      $form['appt']['#options']['All'] = t('All');
      $form['area']['#options']['All'] = t('All');
    }

}


function asc_people_filter_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {
    case 'list':
      $blocks[0]['info'] = t('Active Filters');
      $blocks[0]['cache'] = BLOCK_NO_CACHE;
      $blocks[1]['info'] = t('Appointments');
      $blocks[2]['info'] = t('Research Interests');
      return $blocks;

    case 'view':
      if ($delta == 0) {
        $terms = array();

        if (isset($_GET['area']) && $_GET['area'] != "All") {
          $term = taxonomy_get_term($_GET['area']);
          $terms[] = $term->name;
        }

        if (isset($_GET['appt']) && $_GET['appt'] != "All") {
          $term = taxonomy_get_term($_GET['appt']);
          $terms[] = $term->name;
        }

        $block['subject'] = t('Active Filters');
        $block['content'] = theme('item_list',$terms);
      }      
      elseif ($delta == 1) {
        $list = array();
        $terms = taxonomy_get_tree(2);
        $_GET['area'] ? $area = "&" . $_GET['area'] : "" ;
        foreach ($terms as &$term) {
          $list[] = '<a href="/directory?appt=' . $term->tid . $area . '">' . $term->name . '</a>';
        }
        $block['content'] = theme('item_list',$list);
        $block['subject'] = "";
      }
      elseif ($delta == 2) {
        $list = array();
        $terms = taxonomy_get_tree(1);
        $_GET['appt'] ? $appt = "&" . $_GET['appt'] : "" ;
        foreach ($terms as &$term) {
          $list[] = '<a href="/directory?area=' . $term->tid . $appt . '">' . $term->name . '</a>';
        }
        $block['content'] = theme('item_list',$list);
        $block['subject'] = "";
      }
      return $block;
  }  
}

?>
